### PR TITLE
added metrics

### LINKED ISSUE #50: Add Status check or health monitor

### PR DESCRIPTION
**Pull request by darkhanzhursin**

### CODE REVIEW

**Review by nabil-miu — APPROVED** [review]

**Comment by nabil-miu** [comment]
@darkhanzhursin how can we see the matrix numbers ? if there are new endpoints, could you add them to postman ?

**Comment by darkhanzhursin** [comment]
> @darkhanzhursin how can we see the matrix numbers ? if there are new endpoints, could you add them to postman ?

@nabil-miu I added metrics only to parent CrudController class, so all child classes are measured now: http://localhost:8080/actuator/metrics

f.e.: http://localhost:8080/actuator/metrics/EventController?tag=method:getById counts how many times getById of EventContoller method was called etc.

**Comment by nabil-miu** [comment]
> > @darkhanzhursin how can we see the matrix numbers ? if there are new endpoints, could you add them to postman ?
> 
> @nabil-miu I added metrics only to parent CrudController class, so all child classes are measured now: http://localhost:8080/actuator/metrics
> 
> f.e.: http://localhost:8080/actuator/metrics/EventController?tag=method:getById counts how many times getById of EventContoller method was called etc.

Thanks @darkhanzhursin, can we have a new folder in postman contains examples of the URLs like one that you have shared

**Review by reza-newgen — APPROVED** [review]
import edu.miu.cs545.project.model.entity.StudentDirectory;
import edu.miu.cs545.project.service.StudentDirectoryService;
import io.micrometer.core.instrument.MeterRegistry;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.data.domain.Page;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDate;
import java.util.List;

please remove the space

**Review by reza-newgen — APPROVED** [review]
mport edu.miu.cs545.project.model.entity.ResourceCategory;
import edu.miu.cs545.project.service.CategoryService;
import io.micrometer.core.instrument.MeterRegistry;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

please remove the space

**Review by reza-newgen — COMMENTED** [review]
import edu.miu.cs545.project.service.CrudService;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.MeterRegistry;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;


import java.lang.reflect.Method;
import java.net.URI;
import java.util.List;
import java.util.Optional;


please remove the space .

**Review by reza-newgen — APPROVED** [review]
Please check all import package section and remove spaces.

**Pull request merged**
